version: "3.8"

services:
  webhook-provider:
    build: ./webhook-provider
    container_name: webhook-provider
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./webhook-provider:/app
      - /app/node_modules

  webhook-receiver:
    build: ./webhook-receiver
    container_name: webhook-receiver
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./webhook-receiver:/app
      - /app/node_modules
